"""empty message

Revision ID: 07be36cf339f
Revises: a40f5aa3451a
Create Date: 2025-10-02 16:03:51.850910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07be36cf339f'
down_revision: Union[str, Sequence[str], None] = 'a40f5aa3451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_clans', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggstore_clans', 'user_id')
    # ### end Alembic commands ###
