"""empty message

Revision ID: 2d7a31ec36bd
Revises: fbcf35dfac8e
Create Date: 2025-09-29 23:19:47.260454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7a31ec36bd'
down_revision: Union[str, Sequence[str], None] = 'fbcf35dfac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('polite', sa.Float(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('skill', sa.Float(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('team_game', sa.Float(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('experience', sa.Integer(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('send_first_message', sa.Boolean(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('five_consecutive_days', sa.Boolean(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('last_activity_day', sa.Date(), nullable=False))
    op.add_column('ggstore_profiles', sa.Column('days_series', sa.Integer(), nullable=False))
    op.drop_column('ggstore_profiles', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('ggstore_profiles', 'days_series')
    op.drop_column('ggstore_profiles', 'last_activity_day')
    op.drop_column('ggstore_profiles', 'five_consecutive_days')
    op.drop_column('ggstore_profiles', 'send_first_message')
    op.drop_column('ggstore_profiles', 'experience')
    op.drop_column('ggstore_profiles', 'team_game')
    op.drop_column('ggstore_profiles', 'skill')
    op.drop_column('ggstore_profiles', 'polite')
    # ### end Alembic commands ###
