"""empty message

Revision ID: 4a77002b7675
Revises: 6b15099ca8bb
Create Date: 2025-11-19 19:21:59.190409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a77002b7675'
down_revision: Union[str, Sequence[str], None] = '6b15099ca8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('goals', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggstore_profiles', 'goals')
    # ### end Alembic commands ###
