"""empty message

Revision ID: 5360c4b7989d
Revises: 4a77002b7675
Create Date: 2025-11-19 19:27:00.553662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5360c4b7989d'
down_revision: Union[str, Sequence[str], None] = '4a77002b7675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ggstore_profiles', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ggstore_profiles', 'goal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
