"""empty message

Revision ID: 6b15099ca8bb
Revises: d721545d9e95
Create Date: 2025-11-17 23:13:56.091265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b15099ca8bb'
down_revision: Union[str, Sequence[str], None] = 'd721545d9e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_clans', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggstore_clans', 'created_at')
    # ### end Alembic commands ###
