"""empty message

Revision ID: 8de820d0c3a3
Revises: 76decd26c150
Create Date: 2025-09-29 20:18:34.000322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de820d0c3a3'
down_revision: Union[str, Sequence[str], None] = '76decd26c150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('ggstore_profiles', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ggstore_profiles', 'is_active')
    # ### end Alembic commands ###
