"""empty message

Revision ID: a40f5aa3451a
Revises: b59674640294
Create Date: 2025-10-02 15:53:48.436813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40f5aa3451a'
down_revision: Union[str, Sequence[str], None] = 'b59674640294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ggstore_clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('demands', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ggstore_clans')
    # ### end Alembic commands ###
