"""empty message

Revision ID: caecf8e9f787
Revises: bb754d194deb
Create Date: 2025-10-03 20:55:10.779513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caecf8e9f787'
down_revision: Union[str, Sequence[str], None] = 'bb754d194deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ggstore_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['ggstore_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('ggstore_profiles', 'game')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('game', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('ggstore_games')
    # ### end Alembic commands ###
