"""empty message

Revision ID: ce3fba7c4edc
Revises: 
Create Date: 2025-09-26 21:20:27.648862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3fba7c4edc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ggstore_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('telegram_tag', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ggstore_profiles')
    # ### end Alembic commands ###
