"""empty message

Revision ID: f3237a51639e
Revises: caecf8e9f787
Create Date: 2025-10-03 20:59:09.497025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3237a51639e'
down_revision: Union[str, Sequence[str], None] = 'caecf8e9f787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggstore_profiles', 'rank')
    op.drop_column('ggstore_profiles', 'five_consecutive_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('five_consecutive_days', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ggstore_profiles', sa.Column('rank', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
