"""empty message

Revision ID: fbcf35dfac8e
Revises: 8de820d0c3a3
Create Date: 2025-09-29 20:59:57.316444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcf35dfac8e'
down_revision: Union[str, Sequence[str], None] = '8de820d0c3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggstore_profiles', sa.Column('teammate_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggstore_profiles', 'teammate_ids')
    # ### end Alembic commands ###
